### ISSUE TITLE
I cannot disable DevMenu

### ISSUE THREAD

**Issue by Eggmanplant** [RSDKModding/RSDKv5-Decompilation#272]
Tried devMenu=0 and devMenu=n

**Comment by Mefiresu** [comment]
Works fine on my end with a standard setup using Data.rsdk (deleting the line works as well).
Make sure you're not in data folder mode (devMenu is always enabled in that mode).

**Comment by Eggmanplant** [comment]
Sorry, I had an unpacked data folder. But please, can you disable the force dev menu mode on data folder?

**Comment by MegAmi24** [comment]
This is original engine behavior, so it will not be disabled.
