### ISSUE TITLE
Crashing on GLFW 3.4

### ISSUE THREAD

**Issue by Eggmanplant** [RSDKModding/RSDKv5-Decompilation#274]
OS: Void Linux
DE: GNOME
Display Server: Wayland
Temporarily fixed by downgrading GLFW to 3.3.
Fails with log output like "GLEW failed to init: Unknown error"
GLFW 3.4 introduces native Wayland. Maybe this also happened on Arch, which had it updated some time ago, but I was playing Minecraft at the time.
Untested on Xorg, but it is laggy for me.

**Comment by Mefiresu** [comment]
Sounds like a GLFW/GLEW regression more than a RSDKv5 bug.
What is your GPU and GPU driver version?

**Comment by Eggmanplant** [comment]
Radeon RX 6600, Mesa (Linux driver) 24.1.3

**Comment by Mefiresu** [comment]
Should be fixed by [7c954fc](https://github.com/RSDKModding/RSDKv5-Decompilation/commit/7c954fc8ab69d8b65a7685164a36ae234860239c) (hacky workaround until GLEW finally gets updated).
