### ISSUE TITLE
[Android] Mod library not found

### ISSUE THREAD

**Issue by BlueStaggo** [RSDKModding/RSDKv5-Decompilation#276]
I'm trying to get this to run on Android and I've managed to get it working without mods. However, I tried compiling the touch controls mod for myself then dropping it into the mods folder but for some reason it says the library file cannot be found.

Here's the log up to the SEGA screen for Sonic Mania: 
[log.txt](https://github.com/user-attachments/files/16576281/log.txt) (unlike touch controls, I did not compile a library for UltrawideMania so ignore that).
The error in question:
```
[MOD] Trying to load mod ManiaTouchControls...
[MOD] ERROR: Failed to open mod logic file -> dlopen failed: library "libManiaTouchControls.so" not found
[MOD] ERROR: Failed to link logic 'mods/ManiaTouchControls/ManiaTouchControls'
[MOD] Failed to load mod ManiaTouchControls.
```

I compiled the library on EndeavourOS (Linux) using cmake with no extra parameters so that might be something I'm doing wrong. The "libManiaTouchControls.so" file is in the same folder as "mod.ini" and I've compiled everything from the latest commits of Sonic-Mania-Decompilation (this means RSDKv5-Decompilation commit 7f91fbc), RSDKv5-Example-Mods and RSDKv5-GameAPI. If it is an issue with me not adding in compiler flags for Android compatibility then I suggest changing the error message to suggest that it found the library file but it could not load it correctly.

**Comment by MegAmi24** [comment]
You're not compiling the mod correctly; [you have to build the mod along with the decomp APK](https://github.com/RSDKModding/RSDKv5-Decompilation/blob/master/dependencies/android/README.md#set-up-symlinks).

**Comment by BlueStaggo** [comment]
Ah, makes sense. Thanks :D

**Comment by BlueStaggo** [comment]
Except uhh I tried symlinking the mod to the android/app/jni directory, rebuilt and nothing happened :(
