### ISSUE TITLE
[Android] Can't get into the actual game

### ISSUE THREAD

**Issue by gityman** [RSDKModding/RSDKv5-Decompilation#280]
### Before opening this issue, I ensure that...

- [X] I have read the [FAQ](https://github.com/RSDKModding/RSDKv5-Decompilation/blob/main/FAQ.md) and confirmed my issue is not mentioned in it.
- [X] I have checked **both open and closed** issues and confirmed this bug has not already been reported.
- [X] I am not asking for tech support (e.g. game closing on startup, error when trying to build, etc).
- [X] I am not asking for modding support or reporting a bug in a specific mod; this bug either occurs without mods enabled or is directly related to the mod loader.
- [X] This bug is not related to any unofficial fork/port of the decompilation, and any issues with those should be kept in the appropriate repository.

### Expected Behavior

Playable From A-Z (probably. I usually don't play this game for long)

### Actual Behavior

Crashes when getting to cutscenes or gameplay

### Steps to Reproduce

I don't think reproducing is even possible. can't put my finger on the what's causing the issue

### Screenshots

https://github.com/user-attachments/assets/db27ef0b-03bd-457d-ac94-f188ffc8b1df

(ignore the background audio that's my brother talking)

### Decompilation Version

RSDKv5 + U 1.1.0: The SHC2024 Update

### Engine Revision

REV0U (RSDKv5U)

### Backend

OpenGL

### Platform

Android

### Additional Comments

phone specs ig:
CPU: Qualcomm Snapdragon 625 (Octo-core ARM Cortex-A53 2Ghz)
GPU: Adreno 506
RAM: 3606 MB
Android OS: Nougat
Phone Model: Asus Zenfone 3 ZE552KL

**Comment by Mefiresu** [comment]
This is a pretty old phone, I'm not surprised the game crashes on it.
Would you be able to build and run the game yourself from Android Studio with the debugger attached? It's hard to guess where the problem is from the video alone.

**Comment by gityman** [comment]
░░░░░▄▄▄▄▀▀▀▀▀▀▀▀▄▄▄▄▄▄░░░░░░░
░░░░░█░░░░▒▒▒▒▒▒▒▒▒▒▒▒░░▀▀▄░░░░
░░░░█░░░▒▒▒▒▒▒░░░░░░░░▒▒▒░░█░░░
░░░█░░░░░░▄██▀▄▄░░░░░▄▄▄░░░░█░░
░▄▀▒▄▄▄▒░█▀▀▀▀▄▄█░░░██▄▄█░░░░█░
█░▒█▒▄░▀▄▄▄▀░░░░░░░░█░░░▒▒▒▒▒░█
█░▒█░█▀▄▄░░░░░█▀░░░░▀▄░░▄▀▀▀▄▒█
░█░▀▄░█▄░█▀▄▄░▀░▀▀░▄▄▀░░░░█░░█░
░░█░░░▀▄▀█▄▄░█▀▀▀▄▄▄▄▀▀█▀██░█░░
░░░█░░░░██░░▀█▄▄▄█▄▄█▄████░█░░░
░░░░█░░░░▀▀▄░█░░░█░█▀██████░█░░
░░░░░▀▄░░░░░▀▀▄▄▄█▄█▄█▄█▄▀░░█░░
░░░░░░░▀▄▄░▒▒▒▒░░░░░░░░░░▒░░░█░
░░░░░░░░░░▀▀▄▄░▒▒▒▒▒▒▒▒▒▒░░░░█░
░░░░░░░░░░░░░░▀▄▄▄▄▄░░░░░░░░█░░
