### ISSUE TITLE
FAQ link in issue template is broken

### ISSUE THREAD

**Issue by Sonic-The-Hedgehog-LNK1123** [RSDKModding/RSDKv5-Decompilation#288]
### Before opening this issue, I ensure that...

- [X] I have read the [FAQ](https://github.com/RSDKModding/RSDKv5-Decompilation/blob/main/FAQ.md) and confirmed my issue is not mentioned in it.
- [X] I have checked **both open and closed** issues and confirmed this bug has not already been reported.
- [X] I am not asking for tech support (e.g. game closing on startup, error when trying to build, etc).
- [X] I am not asking for modding support or reporting a bug in a specific mod; this bug either occurs without mods enabled or is directly related to the mod loader.
- [X] This bug is not related to any unofficial fork/port of the decompilation, and any issues with those should be kept in the appropriate repository.

### Expected Behavior

FAQ link works

### Actual Behavior

FAQ link doesn't work

### Steps to Reproduce

1. Open a new issue
2. Click `Get started`
3. Click the `FAQ` link in the checklist
4. **404**

### Decompilation Version

Irrelevant, this is an issue with this very issue template

### Engine Revision

REV0U (RSDKv5U)

### Backend

DirectX 9

### Platform

Irrelevant

### Additional Comments

The `FAQ` link links to https://github.com/RSDKModding/RSDKv5-Decompilation/blob/main/FAQ.md, but this branch is named `master`, not `main`. So, the link should be https://github.com/RSDKModding/RSDKv5-Decompilation/blob/master/FAQ.md, which actually opens the FAQ page.

**Comment by MegAmi24** [comment]
In the future, please refrain from reporting things like this as a GitHub issue. Tell us in the [REMS Discord server](https://dc.railgun.works/retroengine) instead.

**Comment by Sonic-The-Hedgehog-LNK1123** [comment]
Maybe update the template to make it clear that repo-related issues shouldn't be reported as GitHub issues, because it currently isn't listed in the checklist at all, and doesn't make it obvious where such issues should be reported.

Because of the above, it made the most sense to me to report it here, since it still affected a file in this repo, even if not directly related to the decomp's code itself.
